#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

autoload -U compinit
compinit
. `brew --prefix`/etc/profile.d/z.sh
# Customize to your needs...
autoload -U +X bashcompinit && bashcompinit
eval "$(stack --bash-completion-script "$(which stack)")"

export EDITOR=vim
export VISUAL=vim

# Bookmark for directories
# ========================
export DR=$HOME'/drill-workspace/drill/'
export DP=$HOME'/Dropbox/projects'
export DE=$HOME'/Dropbox/projects/depth-exam'
export P=$DP'/proposal'
export HV=$HOME'/hive-workspace/hive'
# export DRCLI=$HOME'/drill-workspace/drill/contrib/native/client'
# export HS2D=$HOME'/hive-workspace/hs2driver'
# export HS2=$HOME'/hive-workspace/hive/service/src/java/org/apache/hive/service/server'
# export DCUBE=$HOME'/Dropbox/Projects/domcube-src'
# export HS2HOME=/Users/xiaom/hive-workspace/hive/packaging/target/apache-hive-2.0.0-SNAPSHOT-bin/apache-hive-2.0.0-SNAPSHOT-bin
# export RAML=$HOME'/Dropbox/projects/raml-apis'
export R=$HOME'/research'


tufte() {
  pandoc -s -S --toc -c tufte-css/tufte.css $1.org -o $1.html;
}
marked() {
  pandoc -s -S --toc -c $1 $1.org -o $1.html;
}

# Alias for OS X Management
# =========================
alias CleanDupOpenWith="/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user"

# http://www.makeuseof.com/tag/these-6-awesome-terminal-commands-will-boost-your-macbook/

alias ShowDock="defaults write com.apple.dashboard mcx-disabled -boolean YES && killall Dock"
alias HideDock="defaults write com.apple.dashboard mcx-disabled -boolean NO && killall Dock"
alias HideDesktopIcons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias ShowDesktopIcons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias HideApptivateMenuBar="defaults write se.cocoabeans.apptivate TAShowStatusbarIcon 0"

# - Disable a service `sudo launchctl unload -w /Library/LaunchDaemons/com.foundationdb.fdbmonitor.plist`
alias ShowIP="ifconfig en0 | awk '/inet / {print $2}'"
alias TurnOffSpotlight="sudo mdutil -a -i off"
alias TurnOnSpotlight="sudo mdutil -a -i on"
alias DisableAWDL="ifconfig awdl0 down"
alias GenRandMac="openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//'"

# - QuickLook:
# qlmanage -p FILE_PATH

# Alias for Apps
# ==============
alias vi='/Applications/MacVim.app/Contents/MacOS/Vim'
alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'

# `open -a Emacs` seems smart enough to choose opening with emacsclient.
# function open_with_emacs () {
#     emacsclient --no-wait $1
#     # http://www.bash2zsh.com/zsh_refcard/refcard.pdf
#     if [[ $? -ne 0 ]]; then
#         open -a Emacs $1
#     fi;
# }
alias em='open -a Emacs'
alias gl='git lg | less'
alias sql=$(brew list sqlite | grep 'bin/sqlite3')
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

# Hadoop
# ------
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export SCALA_HOME=/usr/local/opt/scala/idea
export M2_HOME=/usr/local/Cellar/maven/3.3.9/libexec

# Docker
# ------

# - ENV by Boot2Docker
#export DOCKER_HOST=tcp://192.168.59.103:2376
#export DOCKER_CERT_PATH=/Users/xiaom/.boot2docker/certs/boot2docker-vm
#export DOCKER_TLS_VERIFY=1

# - get latest container ID
alias dl="docker ps -l -q"
alias dps="docker ps"
alias dpa="docker ps -a"
alias di="docker images"

# - get container IP
alias dip="docker inspect --format '{{ .NetworkSettings.IPAddress }}'"

# - run deamonized container, e.g., $dkd base /bin/echo hello
alias dkd="docker run -d -P"

# - run interactive container, e.g., $dki base /bin/bash
alias dki="docker run -i -t -P"
# - remove unnamed images
drmi () { docker rmi -f $(docker images | grep none | awk '{print $3}')}
drm () { docker rm -f $(docker ps -aq) }
dstop() { docker stop $(docker ps -a -q); }

# - Dockerfile build, e.g., $dbu tcnksm/test 
dbu() { docker build -t=$1 .; }

# - show all alias related docker
dalias() { alias | grep 'docker' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort; }

