#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

autoload -U compinit
compinit
. `brew --prefix`/etc/profile.d/z.sh
# Customize to your needs...

# PATH and other system-wide env var
# ==================================

# - about $path in zsh http://j.mp/1aHdLxH
typeset -U path
path=($HOME/bin
    $HOME/anaconda/bin
    /usr/local/bin
    /Library/TeX/texbin
    $path)
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin:$HOME/Library/Haskell/bin
export EDITOR=vim
export VISUAL=vim

# Bookmark for directories
# ========================
export DRCLI=$HOME'/drill-workspace/drill/contrib/native/client'
export DR=$HOME'/drill-workspace/drill/'
export DE=$HOME'/Dropbox/projects/depth-exam'
export HV=$HOME'/hive-workspace/hive'
export HS2D=$HOME'/hive-workspace/hs2driver'
export HS2=$HOME'/hive-workspace/hive/service/src/java/org/apache/hive/service/server'
export DCUBE=$HOME'/Dropbox/Projects/domcube-src'
export HS2HOME=/Users/xiaom/hive-workspace/hive/packaging/target/apache-hive-2.0.0-SNAPSHOT-bin/apache-hive-2.0.0-SNAPSHOT-bin

# Alias for OS X Management
# =========================
alias CleanDupOpenWith="/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user"

# http://www.makeuseof.com/tag/these-6-awesome-terminal-commands-will-boost-your-macbook/

alias ShowDock="defaults write com.apple.dashboard mcx-disabled -boolean YES && killall Dock"
alias HideDock="defaults write com.apple.dashboard mcx-disabled -boolean NO && killall Dock"
alias HideDesktopIcons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias ShowDesktopIcons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias HideApptivateMenuBar="defaults write se.cocoabeans.apptivate TAShowStatusbarIcon 0"

# - Disable a service `sudo launchctl unload -w /Library/LaunchDaemons/com.foundationdb.fdbmonitor.plist`
alias ShowIP="ifconfig en0 | awk '/inet / {print $2}'"
alias TurnOffSpotlight="sudo mdutil -a -i off"
alias TurnOnSpotlight="sudo mdutil -a -i on"
alias DisableAWDL="ifconfig awdl0 down"
alias GenRandMac="openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//'"

# - QuickLook:
# qlmanage -p FILE_PATH

# Alias for Apps
# ==============
alias vi='/Applications/MacVim.app/Contents/MacOS/Vim'
alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
alias em='open -a Emacs'
alias gl='git lg | less'



# Hadoop
# ------
export JAVA_HOME=`/usr/libexec/java_home -v 1.7`
export SCALA_HOME=/usr/local/opt/scala/idea
export M2_HOME=/usr/local/Cellar/maven/3.3.3/libexec

# Docker
# ------

# - ENV by Boot2Docker
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/xiaom/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

# - get latest container ID
alias dl="docker ps -l -q"
alias dps="docker ps"
alias dpa="docker ps -a"
alias di="docker images"

# - get container IP
alias dip="docker inspect --format '{{ .NetworkSettings.IPAddress }}'"

# - run deamonized container, e.g., $dkd base /bin/echo hello
alias dkd="docker run -d -P"

# - run interactive container, e.g., $dki base /bin/bash
alias dki="docker run -i -t -P"
# - remove unnamed images
drmi () { docker rmi -f $(docker images | grep none | awk '{print $3}')}
drm () { docker rm -f $(docker ps -aq) }
dstop() { docker stop $(docker ps -a -q); }

# - Dockerfile build, e.g., $dbu tcnksm/test 
dbu() { docker build -t=$1 .; }

# - show all alias related docker
dalias() { alias | grep 'docker' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort; }

